// Code generated by go-swagger; DO NOT EDIT.

// Package handler bitlyButNot
//
//  This is a simple API for shortening links
//  Schemes:
//    http
//  Host: localhost
//  BasePath: /
//  Version: 1.0.0
//  Contact: <pimonowlad@gmail.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package handler
