// Code generated by go-swagger; DO NOT EDIT.

package handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API for shortening links",
    "title": "bitlyButNot",
    "contact": {
      "email": "pimonowlad@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "paths": {
    "/": {
      "post": {
        "description": "Adds a new pair of short-original link",
        "summary": "creates new short link",
        "operationId": "postLink",
        "parameters": [
          {
            "description": "Original link to save",
            "name": "originalLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{shortLink}": {
      "get": {
        "description": "By passing in the short link, you can retrieve original link\n",
        "summary": "gets original link",
        "operationId": "getLink",
        "parameters": [
          {
            "type": "string",
            "description": "pass a short link to get original one",
            "name": "shortLink",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "properties": {
        "longLink": {
          "type": "string",
          "minLength": 1
        },
        "shortLink": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is a simple API for shortening links",
    "title": "bitlyButNot",
    "contact": {
      "email": "pimonowlad@gmail.com"
    },
    "version": "1.0.0"
  },
  "host": "localhost",
  "paths": {
    "/": {
      "post": {
        "description": "Adds a new pair of short-original link",
        "summary": "creates new short link",
        "operationId": "postLink",
        "parameters": [
          {
            "description": "Original link to save",
            "name": "originalLink",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/item"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/{shortLink}": {
      "get": {
        "description": "By passing in the short link, you can retrieve original link\n",
        "summary": "gets original link",
        "operationId": "getLink",
        "parameters": [
          {
            "type": "string",
            "description": "pass a short link to get original one",
            "name": "shortLink",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/item"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "item": {
      "type": "object",
      "properties": {
        "longLink": {
          "type": "string",
          "minLength": 1
        },
        "shortLink": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
