// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ineverbee/bitlybutnot/models"
)

// GetLinkOKCode is the HTTP code returned for type GetLinkOK
const GetLinkOKCode int = 200

/*GetLinkOK OK

swagger:response getLinkOK
*/
type GetLinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewGetLinkOK creates GetLinkOK with default headers values
func NewGetLinkOK() *GetLinkOK {

	return &GetLinkOK{}
}

// WithPayload adds the payload to the get link o k response
func (o *GetLinkOK) WithPayload(payload *models.Item) *GetLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get link o k response
func (o *GetLinkOK) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetLinkDefault error

swagger:response getLinkDefault
*/
type GetLinkDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLinkDefault creates GetLinkDefault with default headers values
func NewGetLinkDefault(code int) *GetLinkDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLinkDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get link default response
func (o *GetLinkDefault) WithStatusCode(code int) *GetLinkDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get link default response
func (o *GetLinkDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get link default response
func (o *GetLinkDefault) WithPayload(payload *models.Error) *GetLinkDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get link default response
func (o *GetLinkDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinkDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
