// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/ineverbee/bitlybutnot/models"
)

// PostLinkCreatedCode is the HTTP code returned for type PostLinkCreated
const PostLinkCreatedCode int = 201

/*PostLinkCreated Created

swagger:response postLinkCreated
*/
type PostLinkCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Item `json:"body,omitempty"`
}

// NewPostLinkCreated creates PostLinkCreated with default headers values
func NewPostLinkCreated() *PostLinkCreated {

	return &PostLinkCreated{}
}

// WithPayload adds the payload to the post link created response
func (o *PostLinkCreated) WithPayload(payload *models.Item) *PostLinkCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post link created response
func (o *PostLinkCreated) SetPayload(payload *models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLinkCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostLinkDefault error

swagger:response postLinkDefault
*/
type PostLinkDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostLinkDefault creates PostLinkDefault with default headers values
func NewPostLinkDefault(code int) *PostLinkDefault {
	if code <= 0 {
		code = 500
	}

	return &PostLinkDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post link default response
func (o *PostLinkDefault) WithStatusCode(code int) *PostLinkDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post link default response
func (o *PostLinkDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post link default response
func (o *PostLinkDefault) WithPayload(payload *models.Error) *PostLinkDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post link default response
func (o *PostLinkDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostLinkDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
