// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostLinkHandlerFunc turns a function with the right signature into a post link handler
type PostLinkHandlerFunc func(PostLinkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostLinkHandlerFunc) Handle(params PostLinkParams) middleware.Responder {
	return fn(params)
}

// PostLinkHandler interface for that can handle valid post link params
type PostLinkHandler interface {
	Handle(PostLinkParams) middleware.Responder
}

// NewPostLink creates a new http.Handler for the post link operation
func NewPostLink(ctx *middleware.Context, handler PostLinkHandler) *PostLink {
	return &PostLink{Context: ctx, Handler: handler}
}

/* PostLink swagger:route POST / postLink

creates new short link

Adds a new pair of short-original link

*/
type PostLink struct {
	Context *middleware.Context
	Handler PostLinkHandler
}

func (o *PostLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostLinkParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
